#!/bin/bash

bash <(curl -s https://raw.githubusercontent.com/Dr0ff/Useful-scripts/refs/heads/main/tt.logo.sh)

sudo -v
echo -e "\n\e[33m Этот скрипт производит очистку ноды и переустанавливает базу данных сети из снапшота!\e[0m"
echo -e "\n\e[32m Ссылку на снапшот можно взять на сайте \e[34m https://polkachu.com/tendermint_snapshots/stargaze\e[0m"
echo -e "\e[32m Правый клик на файле для загрузки и там выбрать\e[33m \"Скопировать адрес\"\e[0m"
read -p "Вставьте сюда ссылку на снапшот: " SNAP_LINK
echo -e "\n\e[33m Для продолжения нажмите любую клавишу \e[0m"
read -p ""
wget -O stargaze_latest.tar.lz4 $SNAP_LINK --inet4-only
sudo systemctl stop stargaze.service
cp $HOME/.starsd/data/priv_validator_state.json $HOME/.starsd/priv_validator_state.json.backup
starsd tendermint unsafe-reset-all --home $HOME/.starsd --keep-addr-book
rm -r ~/.starsd/wasm
lz4 -c -d stargaze_latest.tar.lz4  | tar -x -C $HOME/.starsd
mv $HOME/.starsd/priv_validator_state.json.backup $HOME/.starsd/data/priv_validator_state.json
sudo systemctl start stargaze.service
sudo journalctl -u stargaze -f --output cat
rm -v stargaze_latest.tar.lz4
